# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'NewBuckitApp' do

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  pod 'Koloda', '~> 4.3.1'
  pod 'SideMenu'
  pod 'Cloudinary', '~> 2.0'
  pod 'RandomKit', '~> 5.2.3'
  pod 'IQKeyboardManagerSwift'
  pod 'MaterialComponents'


  # Pods for BuckitTestingWithArchitecture

  target 'NewBuckitAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewBuckitAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
